planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.0  # Max motion length
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0  # Max motion length
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0  # Max motion length
arm:
  planner_configs:
    - SBLkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
  projection_evaluator: joints(shoulder_joint,elbow_joint)
  longest_valid_segment_fraction: 0.005
