robot_arm:

  # Arm Trajectory Controllers ---------------------------------------
  robot_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3


  # Gripper Trajectory Controllers ---------------------------------------
  robot_arm_gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_4

